name: docker-image-ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"  # Trigger on tags starting with "v"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fulstech/docker-ubuntu-chrome-java-graphviz

      - name: Extract image version from tag
        id: extract_version
        if: startsWith(github.ref, 'refs/tags/v')  # Only run if triggered by a tag starting with "v"
        run: echo "CONFLUENCE_IMAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONFLUENCE_IMAGE_VERSION=${{ env.CONFLUENCE_IMAGE_VERSION }}